### 所需要的库

In [1]:
import tensorflow as tf
import cProfile

### TF 2.0 的基本操作

**用tf库进行矩阵计算**

In [16]:
x = [[2., 1.], [2., 1.]]
m = tf.matmul(x, x)
print('x matmul x = {}'.format(m))

x matmul x = [[6. 3.]
 [6. 3.]]


###### **创建一个tensor**

In [17]:
a = tf.constant([[1., 2.], [3., 4.]])
a

<tf.Tensor: id=52, shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

###### **传播(Broadcasting)**

In [18]:
b = tf.add(a, 1)
b

<tf.Tensor: id=54, shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

###### 矩阵对应位置相乘

In [19]:
a*b

<tf.Tensor: id=55, shape=(2, 2), dtype=float32, numpy=
array([[ 2.,  6.],
       [12., 20.]], dtype=float32)>

###### **矩阵乘法**

In [20]:
tf.matmul(a, b)

<tf.Tensor: id=56, shape=(2, 2), dtype=float32, numpy=
array([[10., 13.],
       [22., 29.]], dtype=float32)>

#### 可以用numpy对tf的矩阵进行计算

In [25]:
import numpy as np

In [22]:
np.multiply(a, b)

array([[ 2.,  6.],
       [12., 20.]], dtype=float32)

In [23]:
# tf -> numpy
a.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

#### 梯度计算

In [24]:
w = tf.Variable([[1.]])
with tf.GradientTape() as tape:
    loss = w ** 2
grad = tape.gradient(loss, w)
print(grad)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


#### 模型搭建

In [65]:
# 读取数据
(x_train,y_train),(x_test,y_test) = tf.keras.datasets.mnist.load_data()
x_train = x_train[:10000,:,:]
y_train = y_train[:10000]
x_test = x_test[:1000,:,:]
y_test = y_test[:1000]

In [66]:
x_train.shape

(10000, 28, 28)

In [67]:
x_test.shape

(1000, 28, 28)

In [27]:
y_train[:100]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3, 1], dtype=uint8)

In [68]:
# 数据转化
x_train = tf.cast(x_train[..., tf.newaxis]/255, tf.float32)
x_test = tf.cast(x_test[..., tf.newaxis]/255, tf.float32)

y_train = tf.keras.utils.to_categorical(y_train, 10) # 通过onehot分成10类
y_test = tf.keras.utils.to_categorical(y_test, 10)

In [70]:
x_train.shape

TensorShape([10000, 28, 28, 1])

In [72]:
x_test.shape

TensorShape([1000, 28, 28, 1])

In [24]:
y_train[:100]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 

In [32]:
# 用Sequential的接口建立模型
mnist_model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, [3, 3], activation='relu', input_shape=(28,28,1)),
    tf.keras.layers.Conv2D(64, [3, 3], activation='relu'),
    tf.keras.layers.MaxPool2D(pool_size=(2, 2)),
    tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [33]:
mnist_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 64)        0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 12, 12, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 9216)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               1179776   
_________________________________________________________________
dropout_3 (Dropout)          (None, 128)              

In [39]:
# 用model接口来建立模型
inputs = tf.keras.Input(shape=(28, 28, 1), name='digits')
conv_1 = tf.keras.layers.Conv2D(16, [3, 3], activation='relu')(inputs)
conv_2 = tf.keras.layers.Conv2D(16, [3, 3], activation='relu')(conv_1)
ave_pool = tf.keras.layers.GlobalAveragePooling2D()(conv_2)
outputs = tf.keras.layers.Dense(10)(ave_pool)
mnist_model_2 = tf.keras.Model(inputs=inputs, outputs=outputs)

In [40]:
mnist_model_2.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
digits (InputLayer)          [(None, 28, 28, 1)]       0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 26, 26, 16)        160       
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 24, 24, 16)        2320      
_________________________________________________________________
global_average_pooling2d_2 ( (None, 16)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 10)                170       
Total params: 2,650
Trainable params: 2,650
Non-trainable params: 0
_________________________________________________________________


#### 模型训练

###### Use keras fit method

In [41]:
# recode这里就不一一解释参数了(assignment里会有说明)，我不习惯去背参数，不知道了一般都会通过文档去查阅。(https://tensorflow.google.cn/)
mnist_model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3),
                    validation_split=0.1, shuffle=True,
                    loss = tf.keras.losses.categorical_crossentropy,
                    metrics=['accuracy'])

In [46]:
mnist_model.fit(x_train,y_train,batch_size=128,epochs=3)

Train on 10000 samples
Epoch 1/3
10000/10000 [==============================] - 24s 2ms/sample - loss: 2.2958 - accuracy: 0.1191
Epoch 2/3
10000/10000 [==============================] - 21s 2ms/sample - loss: 2.2761 - accuracy: 0.1531
Epoch 3/3
10000/10000 [==============================] - 20s 2ms/sample - loss: 2.2566 - accuracy: 0.1995


In [47]:
# 只用了1w张图来测试，所以准确率不是很高
mnist_model.evaluate(x_test,y_test)

1000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[2.240073863983154, 0.436]

In [73]:
x_test[0][1]

<tf.Tensor: id=2522, shape=(28, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [78]:
mnist_model.predict([[x_test[0]]])

array([[0.10388506, 0.09370624, 0.09747042, 0.09833953, 0.09994438,
        0.09735147, 0.0944383 , 0.10925248, 0.11045005, 0.09516205]],
      dtype=float32)

###### Use TF 2.0

In [82]:
# load process data
(x_train,y_train),(x_test,y_test) = tf.keras.datasets.mnist.load_data()
x_train = x_train[:10000,:,:]
y_train = y_train[:10000]
x_test = x_test[:1000,:,:]
y_test = y_test[:1000]

In [83]:
# 其实操作和keras差不多，只不过把x_train和y_train打包在一起了
dataset = tf.data.Dataset.from_tensor_slices(
(tf.cast(x_train[...,tf.newaxis]/255, tf.float32),
 tf.cast(y_train,tf.int64)))
dataset = dataset.shuffle(1000).batch(32)

In [84]:
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-3)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_history = []

In [85]:
for epoch in range(5):
    
    for (batch, (images,labels)) in enumerate (dataset):
        
        with tf.GradientTape() as tape:
            
            logits = mnist_model(images,training=True)
            loss_value = loss(labels,logits)
            
        grads = tape.gradient(loss_value,mnist_model.trainable_variables)
        optimizer.apply_gradients(zip(grads,mnist_model.trainable_variables))
        
    print("Epoch {} finishted".format(epoch))

Epoch 0 finishted
Epoch 1 finishted
Epoch 2 finishted
Epoch 3 finishted
Epoch 4 finishted


In [86]:
# 说实话我还是更加喜欢fit的方式，代码看起来比较干净 0.0